[[established_account]]
threshold = 1
public_keys = ["tpknam1qzcrjlea5ey5v56yvx4q0ptuz067rgd03cacwtg0f5tsemvlmdnr7tsazcc"]

[[validator_account]]
address = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:27656"
consensus_key = "tpknam1qpal0gey94q784f09p4lmknyym23r8dyqvlsx7w5wfll9dzumtrmy6kzt9l"
protocol_key = "tpknam1qrtvl3s52trj2qacj3m38urvmfpattqjmqh5q6vtcmgd5z3qc3hqvvppyte"
tendermint_node_key = "tpknam1qqn3wqgdldslwagk6zzjnq8ewsw0wmzprajjqxtrfatyumtvjy6d6gc84f7"
eth_hot_key = "tpknam1qypv77znljd9w0mpm4s7ve3knxfqdvr9fu378mq94mtwjmhghh78zucchgk5m"
eth_cold_key = "tpknam1qypapqlvu9s7xegz6l8j4v3em043k7tydyrvrvllt7lhy973q88rrtqga4ed8"

[validator_account.metadata]
email = "null@null.net"

[[bond]]
source = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
validator = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
amount = "100000"
