# Genesis balances.
#
# This files contains the genesis balances of any tokens present at genesis
# associated with implicit addresses (in the form of public keys) or established
# addresses.
#
# For example:
# ```
# [token.NAM]
# some_pk_bech32m_encoding = 10 # genesis tokens, the amount can have up to 6 decimal places
# ```
#
# The public keys present in here are taken from `pre-genesis/wallet.toml`.
# As for the established addresses, these are derived from their respective
# genesis tx toml files.

[token.NAM]
# albert
tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg = "2000000"
tpknam1qrtpj7fldnq8dpjukye6jskjlr2f7xsk2atz5y3wa378yv8w0l8xy7rj847= "2000000"
# bertha
tnam1q8wnhp0jgpzewqnuwtvw28wj546sx4j73g3lq9ac = "2000000"
tpknam1qrdn4pnry9tmgrth6azjuwv5f758974ej0j34xtye5wq4fqy202825vmlsn= "2000000"
# christel
tnam1q8qpqvc2g8aqmfmpkx7l5vttqdpsjf4yuvt5xz03 = "2000000"
tpknam1qz5h8kwndc7c260xcx2ud3aaegdzpkveyxndhl2zy7pjk0wnl3v2cw8kj07= "2000000"
# daewon
tpknam1qrtaguluxe2370dq8phr3t0d54d8nwg5scp6av7vfnhq04kt9d3fkzea5r6 = "100000000"
# ester
tpknam1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqs74gxv4 = "1000000"
# validator-0
tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh = "200000"
tpknam1qpzrttnzfyt6xfu2vy092eruasll3z52rjfexwapdw0rdww5uktlk3j73dw = "200000"

[token.BTC]
# albert
tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg = "1000000"
# bertha
tnam1q8wnhp0jgpzewqnuwtvw28wj546sx4j73g3lq9ac = "1000000"
# christel
tnam1q8qpqvc2g8aqmfmpkx7l5vttqdpsjf4yuvt5xz03 = "1000000"
# daewon-key
tpknam1qrtaguluxe2370dq8phr3t0d54d8nwg5scp6av7vfnhq04kt9d3fkzea5r6 = "1000000"
# ester-key
tpknam1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqs74gxv4 = "1000000"
# validator-0
tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh = "1000000"

[token.ETH]
# albert
tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg = "1000000"
# bertha
tnam1q8wnhp0jgpzewqnuwtvw28wj546sx4j73g3lq9ac = "1000000"
# christel
tnam1q8qpqvc2g8aqmfmpkx7l5vttqdpsjf4yuvt5xz03 = "1000000"
# daewon-key
tpknam1qrtaguluxe2370dq8phr3t0d54d8nwg5scp6av7vfnhq04kt9d3fkzea5r6 = "1000000"
# ester-key
tpknam1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqs74gxv4 = "1000000"
# validator-0
tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh = "1000000"

[token.DOT]
# albert
tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg = "1000000"
# bertha
tnam1q8wnhp0jgpzewqnuwtvw28wj546sx4j73g3lq9ac = "1000000"
# christel
tnam1q8qpqvc2g8aqmfmpkx7l5vttqdpsjf4yuvt5xz03 = "1000000"
# daewon-key
tpknam1qrtaguluxe2370dq8phr3t0d54d8nwg5scp6av7vfnhq04kt9d3fkzea5r6 = "1000000"
# ester-key
tpknam1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqs74gxv4 = "1000000"
# validator-0
tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh = "1000000"

[token.Schnitzel]
# albert
tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg = "1000000"
# bertha
tnam1q8wnhp0jgpzewqnuwtvw28wj546sx4j73g3lq9ac = "1000000"
# christel
tnam1q8qpqvc2g8aqmfmpkx7l5vttqdpsjf4yuvt5xz03 = "1000000"
# daewon-key
tpknam1qrtaguluxe2370dq8phr3t0d54d8nwg5scp6av7vfnhq04kt9d3fkzea5r6 = "1000000"
# ester-key
tpknam1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqs74gxv4 = "1000000"
# validator-0
tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh = "1000000"

[token.Apfel]
# albert
tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg = "1000000"
# bertha
tnam1q8wnhp0jgpzewqnuwtvw28wj546sx4j73g3lq9ac = "1000000"
# christel
tnam1q8qpqvc2g8aqmfmpkx7l5vttqdpsjf4yuvt5xz03 = "1000000"
# daewon-key
tpknam1qrtaguluxe2370dq8phr3t0d54d8nwg5scp6av7vfnhq04kt9d3fkzea5r6 = "1000000"
# ester-key
tpknam1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqs74gxv4 = "1000000"
# validator-0
tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh = "1000000"

[token.Kartoffel]
# albert
tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg = "1000000"
# bertha
tnam1q8wnhp0jgpzewqnuwtvw28wj546sx4j73g3lq9ac = "1000000"
# christel
tnam1q8qpqvc2g8aqmfmpkx7l5vttqdpsjf4yuvt5xz03 = "1000000"
# daewon-key
tpknam1qrtaguluxe2370dq8phr3t0d54d8nwg5scp6av7vfnhq04kt9d3fkzea5r6 = "1000000"
# ester-key
tpknam1qypvqpzu74nafjahlwyq272dj76qq9rz30dulyc94883tmj893mquqs74gxv4 = "1000000"
# validator-0
tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh = "1000000"
