# Transactions pasted from:
#
# 1. `src/pre-genesis/validator-0/signed-transactions.toml`
# 2. `src/pre-genesis/signed-transactions.toml`

# 1.

[[established_account]]
threshold = 1
public_keys = ["tpknam1qzcrjlea5ey5v56yvx4q0ptuz067rgd03cacwtg0f5tsemvlmdnr7tsazcc"]

[[validator_account]]
address = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:27656"

[validator_account.consensus_key]
pk = "tpknam1qpal0gey94q784f09p4lmknyym23r8dyqvlsx7w5wfll9dzumtrmy6kzt9l"
authorization = "signam1qr3t5n54k2qnpecmfsy5klmmq7jtjs273fpxejdmvltd26ym4uwxr86wx4hlzmcs9qfmx7rlhvqyjfg9y7v3la6vqw8zdj4j03vyrmszmuglwg"

[validator_account.protocol_key]
pk = "tpknam1qrtvl3s52trj2qacj3m38urvmfpattqjmqh5q6vtcmgd5z3qc3hqvvppyte"
authorization = "signam1qzmhxyuwdcs325wpdcqz2cyexlhxphfvfkyhyeu6xjsa8qxdjkurf73v92n3x9jyv7latketzq6dkrskny7ceakz3nhkdquvz2cw9lsp8wyxjy"

[validator_account.tendermint_node_key]
pk = "tpknam1qqn3wqgdldslwagk6zzjnq8ewsw0wmzprajjqxtrfatyumtvjy6d6gc84f7"
authorization = "signam1qrtqmyf8j7g4pxhdttzz5807hsxte2hkl0m7x500jr3ycnsf7m9eauxru56ec82ajwrw5mnt2uwwnqryt9t8ytsvdcxpvac20sj6casdm6wa8u"

[validator_account.eth_hot_key]
pk = "tpknam1qypv77znljd9w0mpm4s7ve3knxfqdvr9fu378mq94mtwjmhghh78zucchgk5m"
authorization = "signam1q9z6fnrw9f2g9rs3yw5ddr9n2rlhnvfj6nfaykvkwu8w4n88tw20ghyms50373v5kr6rn08zcyqjje5qr02n448fejtns9q43u5kq38fqypzeul6"

[validator_account.eth_cold_key]
pk = "tpknam1qypapqlvu9s7xegz6l8j4v3em043k7tydyrvrvllt7lhy973q88rrtqga4ed8"
authorization = "signam1qyfky7u6mhw5049xfp6cq4mtwcme798wsfyahcxfx2t2leanlhxhken872qld892e7f4n29sz8pxuay39eejyk0m0xxz4tj5uv22d2slqqaw3rdd"

[validator_account.metadata]
email = "null@null.net"

[validator_account.signatures]
tpknam1qzcrjlea5ey5v56yvx4q0ptuz067rgd03cacwtg0f5tsemvlmdnr7tsazcc = "signam1qr3qcnzyz5e77y26uckd4nm6mdql0749dvtrrklgfpeknhg3qxm2ddj8gg0z4k57xngn88fukkepc7dzffn97tjhk7h76ux2y824elq9yevthj"

[[bond]]
source = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
validator = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
amount = "100000"

[bond.signatures]
tpknam1qzcrjlea5ey5v56yvx4q0ptuz067rgd03cacwtg0f5tsemvlmdnr7tsazcc = "signam1qqaucmk7nlfrqfk8pvzk63gkvalf76a7trel5j0yfeazlpx9zwezteflldzxtd890dcm9q3nclpgqkmwj05w8h7szep4lw79mk0napgvwnwz5a"

# 2.

[[established_account]]
threshold = 1
public_keys = ["tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"]

[[established_account]]
threshold = 1
public_keys = ["tpknam1qrtpj7fldnq8dpjukye6jskjlr2f7xsk2atz5y3wa378yv8w0l8xy7rj847"]

[[established_account]]
threshold = 1
public_keys = ["tpknam1qrdn4pnry9tmgrth6azjuwv5f758974ej0j34xtye5wq4fqy202825vmlsn"]

[[bond]]
source = "tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg"
validator = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
amount = "20000"

[bond.signatures]
tpknam1qrtpj7fldnq8dpjukye6jskjlr2f7xsk2atz5y3wa378yv8w0l8xy7rj847 = "signam1qpu3zdvx6t72uyq4g8q3yavnwwgp50mfvnsnle2ausuvyke2pns6yhujeh0525cs9m0a8h7m3fmswlg8ffq4kxryqpytac4yyv5f5espapz5vv"
