[[established_account]]
threshold = 1
public_keys = ["tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"]

[[established_account]]
threshold = 1
public_keys = ["tpknam1qrtpj7fldnq8dpjukye6jskjlr2f7xsk2atz5y3wa378yv8w0l8xy7rj847"]

[[established_account]]
threshold = 1
public_keys = ["tpknam1qrdn4pnry9tmgrth6azjuwv5f758974ej0j34xtye5wq4fqy202825vmlsn"]

[[bond]]
source = "tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg"
validator = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
amount = "20000"

[bond.signatures]
tpknam1qrtpj7fldnq8dpjukye6jskjlr2f7xsk2atz5y3wa378yv8w0l8xy7rj847 = "signam1qpu3zdvx6t72uyq4g8q3yavnwwgp50mfvnsnle2ausuvyke2pns6yhujeh0525cs9m0a8h7m3fmswlg8ffq4kxryqpytac4yyv5f5espapz5vv"
