# This file contains hand-written unsigned transactions for localnet with:
#
# - 3 established accounts for "Albert", "Bertha" and "Christel"
# - a bond from "Albert"'s established account to validator-0
#
# Note that 1 localnet user account "Daewon" is left as
# implicit account, so their tokens are kept in the accounts derived from their
# keys used in `balances.toml`.
#
# This file is used to produce `signed-transactions.toml` with
# the `sign-genesis-txs` command.

# Albert
[[established_account]]
threshold = 1
public_keys = ["tpknam1qrtpj7fldnq8dpjukye6jskjlr2f7xsk2atz5y3wa378yv8w0l8xy7rj847"]

# Bertha
[[established_account]]
threshold = 1
public_keys = ["tpknam1qrdn4pnry9tmgrth6azjuwv5f758974ej0j34xtye5wq4fqy202825vmlsn"]

# Christel
[[established_account]]
threshold = 1
public_keys = ["tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"]

##########################################################################################

# Albert bonds to `validator-0`
[[bond]]
source = "tnam1qy0rydkctp5nvx5vnjq80rq0w23dn3mrt5c8lzmg"
validator = "tnam1qy5uswpdgykvmev526vrf8ewczjzwnr0qcyccjwh"
amount = "20000"
